### ISSUE TITLE
Icons in explorer do not correspond

### ISSUE THREAD

**Issue by ltWolfik** [davidhewitt/shebang-language-associator#1]
Thanks for the extension. Works correctly, except icons in explorer do not correspond to language mode.
P.s. If force language mode with 'files.associations' standard settings - icons are correct.

**Comment by davidhewitt** [comment]
Cheers, glad you're finding it useful. I agree it would be great if the icons matched the file type detected from the shebang. Unfortunately I don't think this is possible with the vscode extension api - I'm just setting the language mode of the text editor rather than associating the file permanently with the language.

I'll close this issue for now as I don't think it can be implemented, but please reopen if you believe there's a way (or submit a PR 😀)
