### ISSUE TITLE
Some shebang associations fail when the file name contains `.`

### ISSUE THREAD

**Issue by marlonrichert** [davidhewitt/shebang-language-associator#9]
Given this in `settings.json`:
```json
{
  "shebang.associations": [
    {
      "pattern": "^#autoload$",
      "language": "shellscript"
    },
  ]
}

```
When I open the file `foo.bar` containing this:
```sh
#autoload

echo foo

```
Then the language mode is set to "Plain Text", even though there are **no** file associations defined for `*.bar`.

I would expect the language mode to be "Shell Script".

However, if I remove the `.` from the file name, then it _does_ get identified as "Shell Script".

This problem does not occur when associating, for example, `#compdef .*`.

**Comment by davidhewitt** [comment]
The problem is not the file name, but that `#autoload` is not supported by 1.3.0, the only accepted prefixes are

https://github.com/davidhewitt/shebang-language-associator/blob/fe59c77144df70b7614ef41d6e8cd9a6bf236d54/src/extension.ts#L61-L65

However I see no reason to restrict to an expanding arbitrary set, so I will release 1.4.0 which has no limitation. See #10.
